### ISSUE TITLE
Support POST with Prometheus Origin Type

### ISSUE THREAD

**Issue by ahurtaud** [tricksterproxy/trickster#398]
Hello,

I tried trickster 1.0.1 in between grafana and thanos-query (same prometheus HTTP API).
With thanos I am used to set the datasource with POST method because we sometimes have lots of label key + values and the 300chars limit of GET URL was reached.

However when switching to trickster, a cache key was stored but it never contain any data.
When I switch in grafana datasource the method to GET it works (cached data are retrieved). (But I have again this GET limit issue).

Am I missing something to have POST working?

trickster.conf
```
[frontend]
listen_port = 9090
## Configuration options for mapping Origin(s)
[origins]
  [origins.default]
  origin_type = 'prometheus'
  origin_url = 'http://thanos-world.argos.svc:9090'
[metrics]
listen_port = 8082
[logging]
log_level = 'debug'
```

grafana 6.6.1
trickster 1.0.1
thanos 0.11.0

**Comment by jranson** [comment]
Hi, thanks so much for trying Trickster. You are right that we do not currently support the POST option in Grafana for Prometheus. And we certainly should, since it's part of the Prometheus HTTP API specification, and we definitely want to play nice with that pesky HTTP URL length specification. I will take a look at implementing this; we'll provide a patch in v1.1.0, which should be out within 2 weeks, and will comment here again when that is ready to go. I hope you'll try Trickster again when we have that squared away for you!

**Comment by jranson** [comment]
v1.1, which includes the POST support, is released. Thanks for this feature request!
