### ISSUE TITLE
Most recent time bin gets cached and is not refreshed for InfluxDB

### ISSUE THREAD

**Issue by heliodor** [tricksterproxy/trickster#479]
I've modified the docker demo to show what I mean: https://github.com/heliodor/trickster/tree/main/deploy/trickster-demo

Once you run the docker demo, these two scripts can fill the data:

Backfill 3 hours of data:
```
for INDEX in {0..999}
do
    URL="http://localhost:8086/write?db=_internal"
    TIMESTAMP=`date +%s`
    TIMESTAMP=`expr $TIMESTAMP - 10 \* $INDEX`000000000
    PAYLOAD="server_test,host=server01,region=us-west value=$RANDOM $TIMESTAMP"
    curl -i -X POST "$URL" --data-binary "$PAYLOAD"
done
```

Infinite loop to add new data:
```
while true
do
    URL="http://localhost:8086/write?db=_internal"
    TIMESTAMP=`date +%s`000000000
    PAYLOAD="server_test,host=server01,region=us-west value=$RANDOM $TIMESTAMP"
    curl -i -X POST "$URL" --data-binary "$PAYLOAD"
    sleep 1
done
```

Load the example dashboard:
http://localhost:3000/d/jqpfRqNGz/trickster-influxdb?orgId=1&refresh=5s&from=now-1h&to=now

Keep hitting the refresh button. On my end, I only see the top panel (influx direct) displaying new data.

I've also tried with `backfill_tolerance_secs = 60` but that did not seem to make a difference.

Not sure if it's a bug or I'm just confused by the default behavior.

**Comment by jranson** [comment]
@heliodor thanks for reporting this. In the docker-compose file, the trickster docker tag is currently `tricksterproxy/trickster:1.1.0-beta`. This is my fault - i failed to update it to `tricksterproxy/trickster:1.1` in the compose file. If you change that tag in your docker compose, memory should work right away. You will likely need to delete the contents of `./docker-compose-data/trickster-data` for the middle chart (filesystem) to work properly. I will update the tag in our official demo files, and wait for your confirmation that this fixes up your issue, and then we'll close it out. Thanks again for this report!

**Comment by jranson** [comment]
Oh - and also, check out the `backfill_tolerance_secs` configuration option, which should correct the cached empty results you are seeing. With your demo project, setting it to 30 seconds seems to  take care of it. More detail is available in #435.

**Comment by heliodor** [comment]
I'm having a hard time understanding the philosophy of Trickster in its current incarnation. Or maybe I'm misunderstanding something.

It sounds like Trickster caches everything, including the latest time interval/bin. `backfill_tolerance_secs` can delay the caching of the latest time interval.

Meanwhile, most dashboards show data aggregated into time intervals where the one latest time interval is constantly changing as new data arrives. The rest of the time intervals are not ever going to change (assuming no data deletion).

The only sensible thing that a caching system should do, is cache everything except the latest time interval. The size of that interval should be inferred from the query instead of being hard-coded as the config param `backfill_tolerance_secs`.

So, am I understanding this correctly? Does Trickster cache the latest time interval too once `backfill_tolerance_secs` seconds have passed? If so, why?

**Comment by jranson** [comment]
You are understanding the functionality correctly as it works in Trickster right now. We plan to change this in Trickster 2.0, so that instead of providing a duration in seconds, the operator would provide the # of time intervals from real-time that are not cacheable, so a value like 1 or 2 would work generically for any dashboard, regardless of the query's time interval step size. Since we try to be compatible with many TSDB's (not just Influx) we can't really enforce default logic like "don't cache the last time interval", since with other backends like Prometheus, backfill tolerance is not necessarily required. That is why it is configurable. When we release 2.0 with the changed feature, I'll make sure we include the configuration, commented out, in the 'simple' configuration examples and docker-compose. We'll also look at provider-speciifc defaults (e.g., perhaps by default, new_config_name=1 for InfluxDB, but =0 for Prometheus, etc). Thanks again for the feedback!

**Comment by jranson** [comment]
@heliodor we've released v1.1.3 which includes the image tag correction i mentioned above, and provided the configuration to avoid preliminary results from being cached . Anything else we can do before closing out this issue?

**Comment by heliodor** [comment]
Yeah, go ahead and close it. I look forward to version 2!

**Comment by jranson** [comment]
Sounds good, thanks! We are too :-D
